### ISSUE TITLE
Error verifying Windows Reserved partitions

### ISSUE THREAD

**Issue by agnivo007** [redorescue/redorescue#40] opened 2020-09-09 18:38 UTC
The partition sda2 being processed (as you see in the screenshot) is a windows reserved partition.
Would like to know what the actual issue is...
![Screenshot_20200910_000613](https://user-images.githubusercontent.com/69066549/92639529-8deb2d80-f2f9-11ea-9b53-c94d27230cd1.png)

**Comment by zebradots** [comment] 2020-09-13 01:36
Hi @agnivo007, and thanks for your continued input! This is strange. Out of curiosity, can you open Gparted from the start menu, right-click the Windows Reserved partition, and run a filesystem check on this partition?

**Comment by agnivo007** [comment] 2020-09-13 10:48
I wonder if a FS check would be feasible as it isn't an unsupported element in gparted or even linux.

I'll retry creating a backup+verify and check for the log if it reappears again...

**Comment by zebradots** [comment] 2020-09-14 23:53
The screenshot appears to report the partition as a FAT32. Is this operation not supported by Gparted?

**Comment by zebradots** [comment] 2020-10-11 03:32
Hi @agnivo007, please check https://github.com/redorescue/redorescue/issues/44 and see if it is possible that this error was caused by the bug described there. The fix will be included in version 2.0.6.

**Comment by zebradots** [comment] 2020-10-11 04:16
@agnivo007, please also review a very similar report on the forums at https://sourceforge.net/p/redobackup/discussion/help/thread/c17a65cb06/?limit=25#65b6/3149. There may be an issue with these Windows Reserved partitions, which seem to be backed up without any problems, but then cannot be verified or restored properly.

If the fix for issue https://github.com/redorescue/redorescue/issues/44 (included in 2.0.6) does not correct this issue for you, then we need to turn our focus to this particular partition type, which may be causing problems because it is not a standard filesystem. Forum user Philip has attached a backup image set for testing.

**Comment by zebradots** [comment] 2020-10-11 18:50
In our testing, these partitions are restoring correctly, but _verification_ is failing. Since these partitions are handled by `partclone.dd` there is no way to truly verify the integrity of the data, as it is merely copied byte-for-byte without the organization of any underlying filesystem. We need to reassess whether verifying these partitions is even warranted.

If anyone else has input regarding this issue, please comment.

**Comment by zebradots** [comment] 2020-10-11 20:02
Raw partitions imaged with `partclone.dd` such as "Microsoft reserved" partitions contain no valid filesystem, and there is no `partclone` binary to determine if the image is valid. Verification fails for these partitions.

Partitions such as these have no filesystem, but contain raw binary data rather than files. As such, there is no way to validate the filesystem because it has no headers to check. The image was taken with `dd` and will be restored with `dd`, so there is nothing to verify. The same is true of an encrypted partition: the binary data can be backed up and restored byte-for-byte, but there is no way to run a filesystem integrity check to verify its validity.

In the future we may be able to run the `pigz --test` command to verify the integrity of the archive, but (a) this provides no output and no progress, and (b) still does not verify the integrity of the data it contains. First we must address the immediate problem: verifying images suggests there is a problem when in fact there is not. For now we will disable the selection checkboxes for verifying raw partitions with commit https://github.com/redorescue/redorescue/commit/001ca7ae1846a1b56afbc089017d54025a8a6723.

Given the urgency of this change (as it will no doubt confuse users into thinking their backup image is invalid) we will release 2.0.7 in the next few days.

**Comment by zebradots** [comment] 2020-10-13 01:50
On the SourceForge discussion forum, the user **Philip** encountering this same issue writes:

> I have just created a new image, with the "Microsoft reserved" partition (on my laptop). I then restored it to a new drive. When I try to verify it, the "Microsoft reserved" partition gives the usual error. However, it appears to have been restored without a problem. I am using it now.

This report confirms what we're seeing in testing, so we're comfortable closing this issue once the next release (2.0.7) is completed.

**Closed** 2020-10-13 02:51 UTC
Labels: bug
