### ISSUE TITLE
Target computer's time resets to GMT after booting with Redo

### ISSUE THREAD

**Issue by IlgazC** [redorescue/redorescue#30] opened 2020-08-14 09:14 UTC
I have 2 POS computers which runs Windows 10. I use Redo Backup weekly to backup their images to an external USB.

When I reboot to after backing up I notice time is set to GMT instead of Turkish time which is GMT+3. It creates issue with the POS software we use. As you probably know, Windows does NTP sync in absurdly long periods (3 days?) so you have to manually sync the time.

I am available for testing etc.

**Comment by zebradots** [comment] 2020-08-14 22:49
Hi @IlgazC, thanks for the input! There is something that may work to fix this issue, but it will require a little bit of testing. When Linux is booted, the automatic update of the time via `timedatectl` may be the issue since timezones can't be automatically detected. Here are the steps to try:

1. Power the Windows POS machine off
2. Disconnect its network cable (or if it uses WiFi, do not connect after rebooting)
3. Boot into Redo
4. Right-click the taskbar and open a command terminal
5. Enter `timedatectl set-local-rtc 1 --adjust-system-clock` to make Linux use local time
6. Connect to the network
7. Wait a minute or two and then run `timedatectl` (without any arguments) to make sure it returns `RTC in local TZ: yes` and `NTP synchronized: yes` to confirm the time has been updated over the network
8. Power off, boot into Windows, and see if the time is correct

The theory is that if we set Linux to use the local time before it syncs with a network time server, it might prevent the time from being adjusted as you describe. After booting into Windows, if you discover that this made no difference, then try this:

1. Sync the time in Windows to make it correct again
2. Power off, disconnect network
3. Boot into Redo
4. Launch a terminal and enter `timedatectl set-ntp false`
5. Enter `timedatectl` to confirm it says `NTP syncronized: no` and `Network time on: no`
6. Reconnect the network
7. Wait a minute or two and run `timedatectl` again to confirm the above didn't change
8. Power off, boot back into Windows, see if it changed the time

Hopefully the first set of steps listed above will solve it.

**Comment by zebradots** [comment] 2020-08-16 03:51
Hopefully a fix for this issue has been added with https://github.com/redorescue/redorescue/commit/19f71a9e7eb0dd13736f3eb4ac6ed283cc6754fb. The command `systemctl disable systemd-timesyncd.service` should prevent NTP sync from updating the system time, and in addition, the addition of the `/etc/adjtime` file which instructs the system to use the local time (RTC) should prevent this issue from affecting Windows users. This change will be part of version 2.0.5 when it is released.

**Comment by IlgazC** [comment] 2020-08-16 04:25
I was planning to test in 1-2 hours. Should I test the 2.0.5 when it ships?

**Comment by zebradots** [comment] 2020-08-20 03:40
The ISO for 2.0.5 will be available for download in the next few hours!

**Comment by agnivo007** [comment] 2020-08-25 10:12
Today after booting 2.0.5, I saw correct time in taskbar.

**Comment by zebradots** [comment] 2020-08-25 14:11
Excellent. Just to clarify for anyone else reading this, **the time shown in Redo will likely always be off by the same number of hours your system is offset from UTC**. This is expected behavior and isn't likely to be fixed, considering every live OS installer prompts you for the timezone (since it can't be reliably autodetected). The issue here was that users were finding their time in Windows had been changed after using Redo, and that's what this commit was intended to fix.

**Closed** 2020-10-11 03:33 UTC
Labels: enhancement
