### ISSUE TITLE
Prevent Win10 BSOD (Invalid Boot Device) when restoring to different PC

### ISSUE THREAD

**Issue by PizzaProgram** [redorescue/redorescue#39] opened 2020-09-09 15:31 UTC
I came across a problem I can not solve any more with Redo:
 - The latest version of Win10 can not start if placed to an other PC (with different motherboard) after doing a:
   backup+restore = clone.  
 _(Blue Screen error while loading, not possible to start in safe mode, repair does not help, etc...  )_
  
Other products, like AOMEI offer a solution for that, like here:   
https://www.ubackup.com/windows-10/move-hard-drive-to-new-computer-windows-10.html
 _(See "Universal Restore" checkbox)_
  
- Would it be possible to **built in** a similar funktion?  
- Do we now how do they do it?
- Or is it possible to "repair with a tool" which would be built into the ISO ?

**Comment by agnivo007** [comment] 2020-09-09 18:50
Is is an issue with disk uuid's ? Do you know?

**Comment by PizzaProgram** [comment] 2020-09-09 19:20
@agnivo007 I don't think so. Except MS programmed into the latest version some kind of "protection".
But usually those problems make the Windows only "not registered", but still bootable.

**Comment by agnivo007** [comment] 2020-09-10 07:30
Yes, should be bootable yet unactivated on restore. There are disk uuids, BIOS uuids and even windows uuids. The universal restore you mentioned probably replaces/corrects the above on the restored system.

**Comment by zebradots** [comment] 2020-09-13 01:23
Redo is designed to backup and restore a system, which results in an exact duplicate of the image. What you're seeing is a well-documented issue. Different hardware or slight changes can break Windows, hence the warning in Redo's [README](https://github.com/redorescue/redorescue/). Sometimes it won't boot at all.

Redo wasn't really designed for what you're trying to do, but that's not to say it can't be done. If a Linux-based tool exists to help Windows image cope with hardware changes, we can certainly include it. Does Clonezilla or any other project offer this already? To be clear, Redo is OS-agnostic, and engineering a solution is beyond the scope of the project.

**Comment by agnivo007** [comment] 2020-09-13 05:38
Right, if there exists an algo or program or library that you can refer to and it can be included in redo, I guess @zebradots might look into this... What I think is more research and input is needed if you want this specific feature to be investigated.

**Comment by PizzaProgram** [comment] 2020-09-13 12:20
Thanks for the replies!
I have found this solution to get rid of the UUIDs:
https://community.twocanoes.com/t/inaccessible-boot-device-after-cloning-internal-partition-to-external-drive/4734/12

and this to change AHCI / RAID:
https://support.thinkcritical.com/kb/articles/switch-windows-10-from-raid-ide-to-ahci

But both method could be run under WinPE only, so it's impossible to run these from under a linux system.
Anyway I could not "repair" with those method either >> still blue screen error.

**Comment by zebradots** [comment] 2020-09-15 00:00
Sometimes there are certain hardware changes that Windows seems unable to overcome, and it seems this is most often related to missing drivers, particularly storage drivers. Some forums suggest trying a Windows utility called `sysprep` before imaging. In any case, it is apparent from all the posts across the web over the past two decades that no bulletproof solution exists!

**Comment by PizzaProgram** [comment] 2020-09-15 08:08
< OFF >  
I've tried `sysprep`. It was a disaster.   
_(Deleted all the 3 users, all printer drivers, etc... Basically I've got back a "fresh install" with a few programs on it.)_  
Probably I've made a mistake too, because I should have had start with a special `sysprep` command **before** creating the accounts, but all those ca. 200 pages of english "dokumentation" were too confusing at the beginning.  
    
Luckily I've made a backup with RedoBackup 5 hours before it destroyed ALL my settings of 3 weeks of work.

**Comment by zebradots** [comment] 2020-10-07 02:33
@PizzaProgram, sorry for your trouble. Windows is really onerous in this regard (presumably to prevent copying), and this makes it difficult to upgrade hardware without running into these issues. Sorry we could not be of further help!

In any case, we're glad to hear that Redo was helpful in creating an image of the working system before things went haywire.

**Closed** 2020-10-31 12:43 UTC
Labels: wontfix
