### ISSUE TITLE
How to fix mismatched GPT and MBR partition

### ISSUE THREAD

**Issue by candrapersada** [redorescue/redorescue#10] opened 2020-06-19 06:24 UTC
How to fix mismatched GPT and MBR partition?
```
MBR: MBR only
BSD: not present
APM: not present
GPT: Damaged
```

**Comment by shasheene** [comment] 2020-06-19 07:21
Please note that the user candrapersada originally created this bug as [Rescuezilla #94](https://github.com/rescuezilla/rescuezilla/issues/94). candrapersada also created [Redo Rescue issue #9](https://github.com/redorescue/redorescue/issues/9), as well as ([Rescuezilla issue #92](https://github.com/rescuezilla/rescuezilla/issues/92) and [Rescuezilla issue #93](https://github.com/rescuezilla/rescuezilla/issues/93)).

Redo Rescue and Rescuezilla are separate projects (and as of writing incompatible with each other).

As I (the Rescuezilla developer) wrote in [Rescuezilla #94](https://github.com/rescuezilla/rescuezilla/issues/94), I tried to reproduce this inconsistent GPT/MBR bug using the latest Rescuezilla (v1.0.6), but have yet been unable to reproduce the issse with Rescuezilla.

I have just also checked if it could be caused by a Rescuezilla v1.0.5/v1.0.5.1/v1.0.6 backup format (which is very similar to Rescuezilla v1.0.4's .backup format) that was attempted to be restored with Redo Rescue v2.0.0, but confirmed that this is not possible as Redo Rescue happens to not proceed with a recovery in this situation. I didn't check the exact Redo Rescue error message, but the virtual dist disk was not modified so I'm comfortable that this was _not_ the cause.

The Redo Rescue v2.0.0 (BETA) release offers capabilities to re-order partitions, so it is my belief that the inconsistent GPT table was most likely introduced through the use of Redo Rescue v2.0.0. **Therefore I am leaving it to the Redo Rescue developer to support this issue.**

(I am continuing efforts to help users better delineate between the two separate projects of Rescuezilla and Redo Recovery through FAQ entries etc.)

**Comment by redorescue** [comment] 2020-06-19 23:58
There is not enough information to replicate this error. Which program generated the output posted above? Can you describe each step that was taken before you arrived at this state?

**It's very important to understand that if selective restore is used to remap source partitions to different target partitions, the drive cannot be expected to boot afterward.** One cannot simply remap partitions and expect the boot loader to work afterward. The baremetal option is the only certain way to backup and restore an operating system and expect it to boot. Data partitions can survive remapping; operating system partitions more than likely cannot. Could this explain what you've run into here?

It is odd that the same issue was created on GitHub for both Redo Rescue and Rescuezilla. It seems extraordinarily unlikely that both programs (which are not presently on the same code base) have resulted in the exact same outcome, but if this is the case, it would almost certainly point to a problem with partclone, which neither Redo nor Rescuezilla maintain.

**Comment by zebradots** [comment] 2020-06-20 20:06
This issue describes the same underlying problem in #9.

**Comment by zebradots** [comment] 2020-06-20 20:11
The latest commit has renamed the restore options to "Full system recovery" and "Restore data only", and now includes a bright orange warning: "Remapping partitions to new targets will render a restored operating system unbootable. This option is for advanced users only."

Had these changes been in place, perhaps this issue would never have arisen, and educating the user through better warnings and descriptions seems to be the only way to prevent misunderstandings here.

Closing this issue as resolved.

**Comment by zebradots** [comment] 2020-06-20 20:13
(Leaving issue open until new 2.0.2 release is tagged)

**Comment by candrapersada** [comment] 2020-06-20 22:30
how to fix without remove data
![VirtualBox_Linux Mint VirtualBox_20_06_2020_22_24_14](https://user-images.githubusercontent.com/36833664/85212770-4e5b1800-b380-11ea-953b-f08a8c2c2461.png)

**Comment by zebradots** [comment] 2020-06-21 01:31
Hi candrapersada,

Can you please tell us which restore method was used: baremetal or selective?

**Comment by candrapersada** [comment] 2020-06-21 02:22
baremetal

**Comment by zebradots** [comment] 2020-06-21 02:29
Thanks! Two more questions:

1. Was the backup restored to (a) a completely blank drive that was new or zeroed out, or (b) a drive that may have contained old data?
2. Was the backup image of (a) a GPT partition table, or (b) an MSDOS partition table?

**Comment by candrapersada** [comment] 2020-06-21 02:36
a completely blank drive that was new or zeroed out
MSDOS partition table

**Comment by zebradots** [comment] 2020-06-21 02:52
Thank you!

1. Is there only one single drive in this system, or are there multiple drives?
2. If a drive was replaced, is it the same bus type (e.g. Virtio, SATA, USB)?

**Comment by candrapersada** [comment] 2020-06-21 02:59
one single drive in this system SATA

**Comment by zebradots** [comment] 2020-06-21 03:24
Thank you for the answers! Based on the information you've provided, we are really at a loss to explain what happened. The drive you restored to is reporting damaged GPT data, but given the steps you took, it should instead read "not present". This means either:

a) other modifications to the drive took place, or
b) the drive was not completely zeroed out.

If a successful backup of a disk that has no GPT partition table is created with Redo 2.0.0+ and restored **IN FULL RECOVERY BARE METAL MODE** with Redo 2.0.0+, it is just not possible for the restored image to have GPT data present.

Redo does not know the difference between GPT and MSDOS partition tables. It simply hands off the partition table description created with `sfdisk` during the backup right back over to `sfdisk` again during the restore, to put everything back how it was. This would not result in the creation of any GPT information on the disk.

GPT information is located at the beginning _and_ end of a disk, so if a disk that once had a GPT table is not _completely_ zeroed out, `sgdisk` will likely report some GPT data (as either "present" or "damaged").

The only other possibility that comes to mind is that another partitioning or backup tool was used that may have modified the partition tables in some way that has resulted in this state.

Is there any other information you have that might help us determine what happened?

**Comment by candrapersada** [comment] 2020-06-21 03:34
yes i used another partitioning tool for convert gpt to mbr without data loss

**Comment by zebradots** [comment] 2020-06-22 02:26
This makes it really difficult to know exactly what happened, but two things are clear:

1. The conversion tool made a change to your partition tables, and
2. Redo could not have written any GPT data to the drive, because none was on there to save.

Redo would only have created a backup of the MSDOS partition table using `sfdisk`, then restored that backup with `sfdisk` (the same tool). No changes are made.

If Redo were to fail to restore a 100% identical system using bare-metal mode, we would have a bug. But in this case, another tool has made changes to the drive, so it's not possible to tell what part Redo played in this.

If you would like to test the latest release, we recommend trying to use _only_ Redo to create a full backup, zeroing the drive out (or swapping it out) and then restoring that backup in bare-metal mode to see if the system was recovered properly. Changing hardware configuration, swapping drives, remapping partitions, or changing partition table types are all recipes for rendering a system unbootable. Even without Redo involved at all, changes like these will nearly always break an operating system installation, making it unbootable.

**Closed** 2020-06-24 07:51 UTC
Labels: documentation, enhancement
