### ISSUE TITLE
Version 3.0.0 boots to text login, prompts for username

### ISSUE THREAD

**Issue by sharicov** [redorescue/redorescue#49] opened 2020-10-20 11:36 UTC
Boots into console, asking for login username

**Comment by agnivo007** [comment] 2020-10-20 19:08
Wait for revised release with firmwares added.

**Comment by zebradots** [comment] 2020-10-22 01:42
This is almost definitely a duplicate of https://github.com/redorescue/redorescue/issues/47.

**Closed** 2020-10-22 03:02 UTC
Labels: duplicate
