### ISSUE TITLE
Dell PCs (and other systems) with UEFI Secure Boot show grub prompt

### ISSUE THREAD

**Issue by IlgazC** [redorescue/redorescue#48] opened 2020-10-16 17:14 UTC
Congratulations for 3.0!

I have written the image to a USB2 drive. Secure boot enabled, it works perfectly on supported Linuxes (Fedora, SUSE). When it boots I am greeted by a Grub shell.

I can give any info or do tests.

I believe it is properly signed otherwise Grub wouldn't appear.

**Comment by PROBLEMCHYLD** [comment] 2020-10-16 19:25
Secure boot is disabled on my system

**Comment by zebradots** [comment] 2020-10-17 03:41
Thanks for opening this issue. It's unclear what circumstances cause this behavior: Are you saying that when the system boots with Secure Boot **enabled** it works as expected, but that it does not work as expected with Secure Boot **disabled**?

**Comment by IlgazC** [comment] 2020-10-17 08:08
> Thanks for opening this issue. It's unclear what circumstances cause this behavior: Are you saying that when the system boots with Secure Boot **enabled** it works as expected, but that it does not work as expected with Secure Boot **disabled**?
> 
> Also, are you seeing this behavior on other machines also, or only this particular hardware?

It boots to GRUB prompt when secure boot enabled/UEFI enabled. MBR boot seems to be OK. It should load Linux but shows GRUB shell. Device is already in secure boot mode, I use OpenSUSE TW and Windows 10. Grub is already working on this machine.

**Comment by IlgazC** [comment] 2020-10-17 08:20
I also have a Mac Mini 2009 (Intel based, EFI) here. It also boots to GRUB prompt.

**Comment by IlgazC** [comment] 2020-10-17 08:35
I downloaded the file again to make sure, it is the exact same file. sha256sum follows:
6b8332012d57f13913031baab56ee9784389237ae6aa44336d264854f39ff27d  redorescue-3.0.0.iso

**Comment by RobertHulsebos** [comment] 2020-10-17 10:44
I have the same here on my Dell XPS 8910 computer. In the UEFI bootmenu I get the option to boot from the USB stick with the iso. But when I do, I only get a grub prompt. Nothing else. System runs Windows 10 only.

**Comment by PROBLEMCHYLD** [comment] 2020-10-17 11:12
Yes, its UEFI related because I can boot off cd with no problem.

**Comment by IlgazC** [comment] 2020-10-17 11:29
For a quick test, I grabbed the latest Debian 10 install image (netboot) from https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-10.6.0-amd64-netinst.iso
It seems to work very fine, booting to Debian Installer not grub.

**Comment by RobertHulsebos** [comment] 2020-10-18 18:27
Tested on my Dell Laptop - same result. Just ending with grub prompt, same as on desktop.
See attached photo for bootmenu...
![IMG_20201018_202037](https://user-images.githubusercontent.com/73020730/96376599-3786cf80-1180-11eb-9bfd-a281b1c9eed6.jpg)

**Comment by geleibo** [comment] 2020-10-18 23:40
Please check the file name in the boot device. If there is a dot, delete it and try again



 
---Original---

**Comment by RobertHulsebos** [comment] 2020-10-19 07:19
> 
> Please check the file name in the boot device. If there is a dot, delete it and try again
> […](#)
> ---Original--- From: "RobertHulsebos"<notifications@github.com&gt; Date: Mon, Oct 19, 2020 02:27 AM To: "redorescue/redorescue"<redorescue@noreply.github.com&gt;; Cc: "Subscribed"<subscribed@noreply.github.com&gt;; Subject: Re: [redorescue/redorescue] HP Pavillon x360 a200nt UEFI secure boot grub prompt (#48) Tested on my Dell Laptop - same result. Just ending with grub prompt, same as on desktop. See attached photo for bootmenu... — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I do not understand what you mean ...

**Comment by geleibo** [comment] 2020-10-19 09:00
No,The file in USB device. (vmlinuz initrd)  I'm write the iso file to usb use Ultraiso . When I check the filename in device,initrd and vmlinuz has a dot  .Then boot failed .  Remove the dot in filename(initrd vmlinuz) boot succee

**Comment by PROBLEMCHYLD** [comment] 2020-10-19 09:31
Whatever the problem is, its located in filesystem.squashfs. When I replaced it with 2.0.7 everything worked again.

**Comment by RobertHulsebos** [comment] 2020-10-19 10:11
> 
> 
> No,The file in USB device. (vmlinuz initrd) I'm write the iso file to usb use Ultraiso . When I check the filename in device,initrd and vmlinuz has a dot .Then boot failed . Remove the dot in filename(initrd vmlinuz) boot succee

Don't see any dot here 
![Uploading IMG_20201019_120729.jpg…]()

**Comment by RobertHulsebos** [comment] 2020-10-19 18:13
> 
> 
> Whatever the problem is, its located in filesystem.squashfs. When I replaced it with 2.0.7 everything worked again.

And how do I do that? ('linux newbie')

**Comment by PROBLEMCHYLD** [comment] 2020-10-20 02:54
Use either 2.0.7 in place of 3.0. I only replace the file to figure out the culprit. I have reported it, if ignored then I'll stick with 2.0.7 because 3.0 is useless.

**Comment by zebradots** [comment] 2020-10-20 03:17
Odd, we have yet to see a machine fail to boot, both with and without Secure Boot enabled, including on virtual hardware. Still searching for more answers as to why this is happening for these particular systems. Please continue to post any information you are able to provide and as soon as we determine a fix for this we'll push a new release.

**Comment by PROBLEMCHYLD** [comment] 2020-10-20 03:58
Maybe it's a bug in the debian version. I'm not going to keep trying to figure it out. 2.0.7 does a good enough job, I'll stick with it.

**Comment by RobertHulsebos** [comment] 2020-10-20 08:37
I have both a desktop and a laptop that show this problem. Both are Dell. I you want me something to test for you, then let me know...

**Comment by RobertHulsebos** [comment] 2020-10-20 08:39
> 
> 
> Use either 2.0.7 in place of 3.0. I only replace the file to figure out the culprit. I have reported it, if ignored then I'll stick with 2.0.7 because 3.0 is useless.

You mean you replaced only the filesystem.squashfs file in the ISO? Where can I get the 2.0.7 version of this file? So I can do the same test here...

**Comment by PROBLEMCHYLD** [comment] 2020-10-20 09:22
My laptop is a dell too. Downgrade to 2.0.7. I remove 3.0 completely because it doesn't work. Rebuild your usb with 2.0.7.  Until these guys figure it out. Whatever they added to filesystem.squashfs is the problem for me and maybe you.

**Comment by RobertHulsebos** [comment] 2020-10-20 09:56
> 
> 
> Yes....My laptop is a dell too. Downgrade to 2.0.7. I remove 3.0 completely because it doesn't work. Rebuild your usb with 2.0.7. Until these guys figure it out. Whatever they added to filesystem.squashfs is the problem for me and maybe you.
> 
> https://sourceforge.net/projects/redobackup/files/

Ok. I'll test tonight with 2.0.7. Just to see if I have the same results. Did not try that version before....

**Comment by agnivo007** [comment] 2020-10-20 19:11
Looks like something with grub cfg or kernel boot parameters...

**Comment by RobertHulsebos** [comment] 2020-10-20 20:13
> 
> 
> > Yes....My laptop is a dell too. Downgrade to 2.0.7. I remove 3.0 completely because it doesn't work. Rebuild your usb with 2.0.7. Until these guys figure it out. Whatever they added to filesystem.squashfs is the problem for me and maybe you.
> > https://sourceforge.net/projects/redobackup/files/
> 
> Ok. I'll test tonight with 2.0.7. Just to see if I have the same results. Did not try that version before....

I tried USB stick with 2.0.7. Somehow my laptop does not see it as a bootable device. Does version 2.0.7 support UEFI + Secure Boot ?

**Comment by IlgazC** [comment] 2020-10-20 20:20
> 
> 
> > > Yes....My laptop is a dell too. Downgrade to 2.0.7. I remove 3.0 completely because it doesn't work. Rebuild your usb with 2.0.7. Until these guys figure it out. Whatever they added to filesystem.squashfs is the problem for me and maybe you.
> > > https://sourceforge.net/projects/redobackup/files/
> > 
> > 
> > Ok. I'll test tonight with 2.0.7. Just to see if I have the same results. Did not try that version before....
> 
> I tried USB stick with 2.0.7. Somehow my laptop does not see it as a bootable device. Does version 2.0.7 support UEFI + Secure Boot ?
I believe it is strictly MBR only, there were UEFI requests back in 2.x that is how I know.

**Comment by RobertHulsebos** [comment] 2020-10-20 21:42
> 
> 
> > > > Yes....My laptop is a dell too. Downgrade to 2.0.7. I remove 3.0 completely because it doesn't work. Rebuild your usb with 2.0.7. Until these guys figure it out. Whatever they added to filesystem.squashfs is the problem for me and maybe you.
> > > > https://sourceforge.net/projects/redobackup/files/
> > > 
> > > 
> > > Ok. I'll test tonight with 2.0.7. Just to see if I have the same results. Did not try that version before....
> > 
> > 
> > I tried USB stick with 2.0.7. Somehow my laptop does not see it as a bootable device. Does version 2.0.7 support UEFI + Secure Boot ?
> > I believe it is strictly MBR only, there were UEFI requests back in 2.x that is how I know.

Ok. That explains it....

**Comment by zebradots** [comment] 2020-10-22 01:46
For others finding this thread, please note that 2.0.7 offers neither Secure Boot nor UEFI, and is strictly MBR. This is by design, and for those users who cannot make use of the UEFI ISO (either due to Redo-specific issues or less-than-ideal EFI implementations with their hardware), it is always possible to use the 2.0 series release instead until a workaround for UEFI on these specific machines can be found.

**Comment by zebradots** [comment] 2020-10-22 03:10
(Note: We realize that this issue might affect more than just Dell systems, but this issue description will help new reports find the right issue.)

Could the EFI implementation on affected systems be looking in a case-sensitive directory name at boot time? In other words, could it somehow make a difference whether the directories are named `EFI` or `efi` on some machines? There has to be some common cause that explains this.

**If anyone with an affected machine can execute GRUB commands to help determine what may be different about these systems, it would be greatly appreciated, as we are unable to reproduce this error on any hardware so far.**

**Comment by PROBLEMCHYLD** [comment] 2020-10-22 05:38
Things are working in 3.0.1. Thanks

**Comment by zebradots** [comment] 2020-10-22 14:38
@RobertHulsebos: As you may already know, [Rescuezilla](https://github.com/rescuezilla/rescuezilla) is a fork of a much older version of Redo from 2012. However, the developer recently implemented UEFI support for that project. Out of curiosity, does the latest release of Rescuezilla boot properly in UEFI Secure Boot mode on your hardware?

**Comment by RobertHulsebos** [comment] 2020-10-22 18:17
> 
> 
> @RobertHulsebos: As you may already know, [Rescuezilla](https://github.com/rescuezilla/rescuezilla) is a fork of a much older version of Redo from 2012. However, the developer recently implemented UEFI support for that project. Out of curiosity, does the latest release of Rescuezilla boot properly in UEFI Secure Boot mode on your hardware? **Also, you mentioned in a previous post that you have both a desktop and laptop that were not booting. Does the desktop boot properly on 3.0.1 now?**

On my Dell XPS8190 desktop I have the same result with 3.0.1 as on my laptop - still ending up in grub. So no improvement...
![IMG_20201022_194018](https://user-images.githubusercontent.com/73020730/96913207-a0818680-14a3-11eb-841f-b5b011c78a6b.jpg)

**Comment by RobertHulsebos** [comment] 2020-10-22 18:20
I also tried Rescuezilla 2.0 iso. Booting from same USB stick, same desktop. This seems to work OK for as far as booting is concerned. (I did not test the actual making of a backup)
Let me know if you need any further testing...
![IMG_20201022_195949](https://user-images.githubusercontent.com/73020730/96913455-efc7b700-14a3-11eb-810e-4b06acabac2a.jpg)

**Comment by zebradots** [comment] 2020-10-22 22:38
We suspect that this may have something to do with the following:
```
search --file /REDO --set root
set prefix=($root)/boot/grub
```
Previously, the `grub.cfg` file was copied into the EFI directory in full, but during testing we later created [a simpler file](https://github.com/redorescue/redorescue/blob/master/overlay/image/EFI/debian/grub.cfg) that simply pointed to [the "master" grub.cfg](https://github.com/redorescue/redorescue/blob/master/overlay/image/boot/grub/grub.cfg) file's location. Anyone with an intimate understanding of GRUB is welcome to chime in or take a peek at the steps taken in the `make` script as the ISO is compiled. In the meantime, this is the first place we're going to look.

**Comment by agnivo007** [comment] 2020-10-23 08:11
#51 Hardware/test report can be submitted here if anyone wishes.

**Comment by zebradots** [comment] 2020-10-23 14:36
> #51 Hardware/test report can be submitted here if anyone wishes.

Thank you for creating that thread to track different outcomes.

**Comment by agnivo007** [comment] 2020-10-23 19:10
@zebradots , you may consult and take this issue with the ventoy developers at https://github.com/ventoy with the boot/uefi/grub issue.

They are the boot specialists as far as I've seen and have developed a great product.
I think admin@ventoy.net would be more than helpful to assist, he looks quite active.

**Comment by RobertHulsebos** [comment] 2020-10-23 19:33
> 
> 
> > #51 Hardware/test report can be submitted here if anyone wishes.
> 
> Thank you @agnivo007 for creating that thread to track different outcomes.
> 
> Those with an affected system may try entering the above two lines manually into the GRUB prompt to see if it provides any helpful output or error messages.

I tried the two lines, but they did not give any response at all...
I noticed though, that some other grub commands give an error response.  (see picture) Are they supposed to ?
![IMG_20201023_212920](https://user-images.githubusercontent.com/73020730/97046258-65e91e00-1577-11eb-91ee-f14cd866606e.jpg)

**Comment by agnivo007** [comment] 2020-10-23 20:12
How about:
search --file /REDO --set root
set prefix=($root)/boot/grub
insmod normal
normal

**Comment by zebradots** [comment] 2020-10-24 04:43
Anyone encountering this issue: Please download and try `redorescue-3.0.2-BETA.iso` from the [SourceForge download page](https://sourceforge.net/projects/redobackup/files/redorescue-3.0.2-BETA.iso/download).

**This test release image includes a configuration change that may correct the GRUB boot prompt issue some of you have reported.** If it appears to work, we will push these changes to the repo and finalize a new release for 3.0.2. Unfortunately, we cannot reproduce this error because all our systems boot properly, so this one is difficult to troubleshoot.

**Comment by agnivo007** [comment] 2020-10-24 07:35
Best of luck for the fix...

However, did the insmod normal, normal additions to grub prompt work? Eager to know...

**Comment by RobertHulsebos** [comment] 2020-10-24 08:08
> 
> 
> Best of luck for the fix...
> 
> However, did the insmod normal, normal additions to grub prompt work? Eager to know...

Yes. They did work! After entering the 'normal' command the Redo application is started automatically and I get this ...

![IMG_20201024_100455](https://user-images.githubusercontent.com/73020730/97072894-d7a98200-15e0-11eb-9538-e85e2e70489d.jpg)

**Comment by agnivo007** [comment] 2020-10-24 08:52
Great! Hope @zebradots noted it...
`search --file /REDO --set root
set prefix=($root)/boot/grub
insmod normal
normal`
It was actually a lesson learnt while trying to fix a non booting linux install which dropped off to grub prompt.

**Comment by zebradots** [comment] 2020-10-24 17:01
> ```
> search --file /REDO --set root
> set prefix=($root)/boot/grub
> insmod normal
> normal
> ```

Our understanding is that the `insmod normal` and `normal` commands are probably only necessary once booting has failed and you've landed at GRUB's rescue mode prompt (the mode shown in all the screenshots above). Several documentation pages about GRUB indicate that the `normal` module is usually loaded automatically:

> Once GRUB is thus running, the first thing it will do is to try and load the module called `normal`. (Source: [GRUB 2 on a lower level](http://www.dolda2000.com/~fredrik/doc/grub2))

However, invoking the `normal` module won't work until the `$root` and `$prefix` are set correctly, which is exactly what we've addressed in the beta version released yesterday. Has anyone facing this issue tried the test release yet?

**If the [3.0.2-BETA ISO](https://sourceforge.net/projects/redobackup/files/redorescue-3.0.2-BETA.iso/download) boots properly, we will prepare a final 3.0.2 release immediately.**

**Comment by IlgazC** [comment] 2020-10-24 18:32
> > ```
> > search --file /REDO --set root
> > set prefix=($root)/boot/grub
> > insmod normal
> > normal
> > ```
> 
> Our understanding is that the `insmod normal` and `normal` commands are probably only necessary once booting has failed and you've landed at GRUB's rescue mode prompt (the mode shown in all the screenshots above). Several documentation pages about GRUB indicate that the `normal` module is usually loaded automatically:
> 
> > Once GRUB is thus running, the first thing it will do is to try and load the module called `normal`. (Source: [GRUB 2 on a lower level](http://www.dolda2000.com/~fredrik/doc/grub2))
> 
> However, invoking the `normal` module won't work until the `$root` and `$prefix` are set correctly, which is exactly what we've addressed in the beta version released yesterday. Has anyone facing this issue tried the test release yet?
> 
> **If the [3.0.2-BETA ISO](https://sourceforge.net/projects/redobackup/files/redorescue-3.0.2-BETA.iso/download) boots properly, we will prepare a final 3.0.2 release immediately.**

It works! I tested both "non secure boot" and "secure boot" options. Thanks for your time. HP Pavilion x360 here (I am the original bug reporter)

**Comment by zebradots** [comment] 2020-10-24 18:34
Excellent! We will push the commits and prepare a new release. Thank you so much for taking time to report this issue and confirm that it has been fixed.

**Closed** 2020-10-24 19:50 UTC
Labels: bug

**Comment by agnivo007** [comment] 2020-10-25 08:17
My comment might be too naive, but if any other volume has a "REDO" directory or file entry on it, will not grub be confused with the commit you posted?

**Comment by zebradots** [comment] 2020-10-30 19:11
@agnivo007, you are correct. If another file named "REDO" exists on the boot media, GRUB could mistakenly assume that it was the root location. While this is theoretically possible, we suspect the likelihood is rather slim. Also, this is the same method used since UEFI was introduced, and was already present before the most recent commit referenced above (see https://github.com/redorescue/redorescue/blob/master/overlay/image/boot/grub/grub.cfg, where these lines also appear).

**Comment by MarcelKuesters** [comment] 2022-02-18 12:34
https://github.com/redorescue/redorescue/issues/18#issuecomment-1044451065
