### ISSUE TITLE
auto Shutdown/Restart

### ISSUE THREAD

**Issue by candrapersada** [redorescue/redorescue#19] opened 2020-07-21 12:11 UTC
how to auto Shutdown/Restart after the Backup/Restore is complete?

**Comment by zebradots** [comment] 2020-07-22 00:53
Hello! There is no built-in way to automatically shutdown or restart once an operation is complete. By design, you must acknowledge the status of the operation before exiting the application. We believe it is vital on operations great importance to be informed of potential issues that were encountered, and to have an opportunity to carefully review the logs for any warnings or errors, including any unknown or unhandled messages, before rebooting into a system that could potentially be corrupted or incomplete.

On the other hand, shutting the system down is as simple as clicking the "power" icon on the bottom of the screen, and the entire process takes about two seconds on modern hardware.

**Comment by agnivo007** [comment] 2020-08-01 05:50
I agree, clicking power icon and shutting down is almost instantaneous...

**Comment by zebradots** [comment] 2020-08-07 21:44
Closing this issue. For the reasons above, we've decided not to implement this function. Thanks for the suggestion and continued input!

**Closed by zebradots** 2020-08-07 21:44 UTC
Labels: wontfix
